name: Sync themes

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "themes/**"

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Send sync request
        run: |
          curl -H 'Content-Type: application/json' https://themes-api.notesnook.com/sync
